# Generated by Django 3.2.2 on 2021-05-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuantityVariant',
            new_name='StockAlert',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_price',
        ),
        migrations.RenameField(
            model_name='stockalert',
            old_name='variant_id',
            new_name='stockalert_id',
        ),
        migrations.RenameField(
            model_name='stockalert',
            old_name='variant_name',
            new_name='stockalert_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stockalert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.stockalert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='./assets/images'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='./assets/images'),
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
