# Generated by Django 3.2.2 on 2021-06-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
