# Generated by Django 3.2.2 on 2021-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210614_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsQuntJson',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
