# Generated by Django 3.2.2 on 2021-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_desc',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='status',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
